#!/bin/bash
# status.sh - status is rendered, never authored.
#
# The v1 session wrote 301k words of coordination prose for 8.4k lines of code,
# and its worst anomaly class — tree-drift, three separate instances — was
# hand-maintained state files going stale in one copy of the tree while being
# updated in another. Both have the same root: narrative artifacts that agents
# must write, rewrite, and re-read every turn.
#
# The fix is not better discipline about editing status.md. It is that nobody
# edits status.md: every fact it contains is already in the ledger, the gates,
# the findings and the evidence log, so the file is a RENDERING. A derived
# artifact cannot drift, costs no agent turns to maintain, and is regenerated
# in milliseconds by anyone who wants a fresh one.
#
# Decisions get the same treatment. v1 kept 49 numbered decisions in a 984-line
# hand-written log that every agent re-read; here a decision is a ledger event
# (`orch decision record`) and the log is a view over those events.

[ -n "${ORCH_STATUS_SOURCED:-}" ] && return 0
ORCH_STATUS_SOURCED=1

# shellcheck source=tier.sh
. "$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)/tier.sh"
# shellcheck source=findings.sh
. "$ORCH_HOME/lib/findings.sh"
# shellcheck source=evidence.sh
. "$ORCH_HOME/lib/evidence.sh"

# ---------------------------------------------------------------------------
# Decisions
# ---------------------------------------------------------------------------

# decision_record <feature> <text> [why]
#
# The number is derived from the count at write time. Two agents recording in
# the same instant could mint the same number; the timestamp and actor still
# disambiguate, and a decision's identity is its ledger row, not its label.
decision_record() {
  local feature="$1" text="$2" why="${3:-}" n
  orch_valid_feature "$feature" || die "decision record: invalid feature '$feature'"
  [ -n "$text" ] || die "decision record: the decision text is required"
  n="$(ledger_read "$feature" | jq -s '[.[] | select(type=="object" and .event=="decision.recorded")] | length + 1' 2>/dev/null)"
  ORCH_LEDGER_FEATURE="$feature" ledger_append decision.recorded \
    n:raw "${n:-1}" text "$text" why "$why"
  printf 'decision #%s recorded for %s.\n' "${n:-1}" "$feature"
}

decision_list() {  # decision_list <feature>
  ledger_read "$1" | jq -r -s '
    [.[] | select(type=="object" and .event=="decision.recorded")]
    | if length==0 then "No decisions recorded."
      else .[] | "#\(.n)  \(.text)\(if (.why // "") != "" then "\n     why: \(.why)" else "" end)  [\(.actor), \(.ts)]"
      end' 2>/dev/null
}

# ---------------------------------------------------------------------------
# The rendering
# ---------------------------------------------------------------------------

status_path() { printf '%s/status.md' "$(orch_feature_dir "$1")"; }

# status_render <feature> -> writes status.md and prints it.
#
# Every section reads from one source of record and names it. Where a source
# has nothing, the section says so — a generated file that omits an empty
# section reads like a file that forgot it.
status_render() {
  local feature="$1" led rung out
  orch_valid_feature "$feature" || die "status render: invalid feature '$feature'"
  [ -d "$(orch_feature_dir "$feature")" ] || die "status render: no such feature $feature"
  led="$(ledger_read "$feature" | jq -c -s '[.[] | select(type=="object")]' 2>/dev/null)"
  rung="$(escalate_rung "$feature")"

  out="$(jq -n -r \
    --arg feature "$feature" \
    --arg now "$(now_iso)" \
    --arg rung "$rung" \
    --arg rung_name "$(escalate_rung_name "$rung")" \
    --arg crew "$(tier_crew "$rung" | sed 's/ /, /g')" \
    --arg confirmed "$(tier_confirmed "$feature")" \
    --arg recommended "$(tier_recommended "$feature")" \
    --arg rec_why "$(tier_recommended_why "$feature")" \
    --argjson led "${led:-[]}" \
    --argjson findings "$(findings_current "$feature" | jq -c -s '.' 2>/dev/null || printf '[]')" \
    --argjson evidence "$(cat "$(evidence_path "$feature")" 2>/dev/null | jq -c -s '[.[] | select(type=="object")]' || printf '[]')" \
  '
  def section(title; body): "\n## \(title)\n\n\(body)\n";
  def none(msg): "_\(msg)_";

  ($led | map(select(.event=="feature.started")) | .[0] // {}) as $start
  | ($led | map(select(.event=="gate.set"))
      | group_by(.gate) | map(.[-1])) as $gates
  | ($led | map(select(.event=="escalation"))) as $esc
  | ($led | map(select(.event=="decision.recorded"))) as $dec
  | ($evidence | group_by(.label) | map(.[-1])) as $ev
  | ($findings | map(select(.status=="open"))) as $open

  | "# \($feature) — status"
  + "\n\n> GENERATED by `orch status render` at \($now) — do not edit."
  + "\n> Every fact below is derived from the ledger, the gates, the findings"
  + "\n> and the evidence log. Editing this file changes nothing and drifts."
  + "\n\n"
  + section("Where it is";
      "- rung **\($rung) · \($rung_name)** — crew: \($crew)"
      + (if $confirmed != "" then "\n- tier `\($confirmed)` confirmed"
         elif $recommended != "" then "\n- tier `\($recommended)` recommended (\($rec_why)) — **unconfirmed, no crew**"
         else "\n- **no tier yet** — `orch tier recommend` is the next step" end)
      + (if ($start.branch // "") != "" then "\n- branch `\($start.branch)` on base `\($start.base // "?")`" else "" end))
  + section("Gates (source: ledger gate.set)";
      if ($gates|length)==0 then none("no gate has been set")
      else ($gates | map("- `\(.gate)`: **\(.state)**"
            + (if (.gate_sha // .sha // "") != "" then " at \((.gate_sha // .sha)[0:12])" else "" end)) | join("\n")) end)
  + section("Open findings (source: findings.jsonl)";
      if ($open|length)==0 then none("none open")
      else ($open | map("- **\(.severity)** \(.id) `\(.file):\(.line)` — \(.claim)") | join("\n")) end)
  + section("Latest attested runs (source: evidence.jsonl — the only writer is `orch run`)";
      if ($ev|length)==0 then none("nothing attested yet")
      else ($ev | map("- `\(.label)`: exit \(.exit_code) at \((.git_sha // "?")[0:12]) (\(.ts))") | join("\n")) end)
  + section("Escalations (source: ledger escalation)";
      if ($esc|length)==0 then none("never escalated")
      else ($esc | map("- \(.from_rung // "?") → \(.rung) (\(.rung_name)): \(.reason)") | join("\n")) end)
  + section("Decisions (source: ledger decision.recorded — append with `orch decision record`)";
      if ($dec|length)==0 then none("none recorded")
      else ($dec | map("- **#\(.n)** \(.text)" + (if (.why // "") != "" then " — \(.why)" else "" end)) | join("\n")) end)
  ')" || die "status render: could not build the rendering"

  printf '%s\n' "$out" > "$(status_path "$feature")"
  printf '%s\n' "$out"
}
